using System;
using System.Collections.Generic;
using UnityEngine;

public static partial class GpsSchema
{
    static List<GpsSectionSpec> Build() => new()
    {
        new GpsSectionSpec("Spieler", "Spielziel", typeof(StatsManager), "",
            new GpsFieldSpec("ultroniumRequiredToWin", "Ultronium zum Gewinnen", min: 1, max: 1000000)),
        new GpsSectionSpec("Spieler", "Energie", typeof(PlayerBaseStats), "",
            new GpsFieldSpec("maxEnergy", "Maximale Energie")),
        new GpsSectionSpec("Spieler", "Energie", typeof(EnergyManager), "",
            new GpsFieldSpec("consumptionMultiplier", "Verbrauchsmultiplikator", min: 0),
            new GpsFieldSpec("idleConsumtion", "Grundverbrauch", min: 0),
            new GpsFieldSpec("moveConsumption", "Zusatz beim Bewegen", min: 0),
            new GpsFieldSpec("diggingConsumption", "Zusatz beim Abbauen", min: 0)),
        new GpsSectionSpec("Spieler", "Energie", typeof(EnergyMonolyth), "",
            new GpsFieldSpec("rechargeCost", "Preis pro Energieeinheit")),
        new GpsSectionSpec("Spieler", "Abbauen", typeof(PlayerBaseStats), "",
            new GpsFieldSpec("miningSpeed", "Basis-Abbaugeschwindigkeit"),
            new GpsFieldSpec("reach", "Abbau-Reichweite", min: 0.01f)),
        new GpsSectionSpec("Spieler", "Cursor", typeof(TileMiner), "",
            new GpsFieldSpec("cursorPulseInterval", "Intervall (s)", min: .05f, max: 10f),
            new GpsFieldSpec("cursorPulseAlphaRange", "Alpha-Bereich", min: 0f, max: 1f),
            new GpsFieldSpec("cursorPulseSize", "Größe (Faktor)", min: 1f, max: 1.5f),
            new GpsFieldSpec("cursorGlowStrength", "Leuchtstärke", min: 0f, max: 3f)),
        new GpsSectionSpec("Spieler", "Cursor", typeof(GameplayTestSettingsData), "",
            new GpsFieldSpec("smartCursorStrokeWidth", "Smartcursor-Strahlbreite (Kacheln)", min: 0f, max: 3f)),
        new GpsSectionSpec("Spieler", "Spitzhacke", typeof(MinerPlayerVisual), "",
            new GpsFieldSpec("miningSwingsPerSecond", "Schläge pro Sekunde", min: .1f, max: 8f),
            new GpsFieldSpec("miningHitOffsetMs", "Treffer-Versatz (ms)", min: -500f, max: 500f)),
        new GpsSectionSpec("Spieler", "Figur", typeof(MinerPlayerVisual), "",
            new GpsFieldSpec("height", "Figurhöhe (m)", min: .3f, max: 4f)),
        new GpsSectionSpec("Spieler", "Kamera", typeof(CameraFollow), "",
            new GpsFieldSpec("smoothSpeed", "Nachführgeschwindigkeit", min: 0.01f),
            new GpsFieldSpec("offset", "Bildausschnitt-Versatz (X/Y)")),
        new GpsSectionSpec("Spieler", "Sichtweite", typeof(Camera), "",
            new GpsFieldSpec("orthographicSize", "Halbe sichtbare Höhe")),
        new GpsSectionSpec("Spieler", "Startressourcen", typeof(GpsPreferences), "",
            new GpsFieldSpec("startingResources", "Startressourcen", applyTime: GpsApplyTime.NewRun)),
        new GpsSectionSpec("Bewegung", "Laufen und Springen", typeof(PlayerBaseStats), "",
            new GpsFieldSpec("moveSpeed", "Laufgeschwindigkeit", min: 0.01f),
            new GpsFieldSpec("jumpHeightBlocks", "Sprunghöhe (Blöcke)", min: 0, max: 100)),
        new GpsSectionSpec("Bewegung", "Bewegungsgefühl", typeof(PlayerMovement), "",
            new GpsFieldSpec("accelTime", "Beschleunigungszeit (s)", min: 0.01f),
            new GpsFieldSpec("decelTime", "Bremszeit (s)", min: 0.01f),
            new GpsFieldSpec("directionChangeDecelTime", "Richtungswechsel-Bremszeit (s)", min: 0.01f),
            new GpsFieldSpec("groundedCoeff", "Beschleunigungsfaktor am Boden", min: 0.01f)),
        new GpsSectionSpec("Bewegung", "Leiter", typeof(PlayerLadder), "",
            new GpsFieldSpec("climbSpeed", "Klettergeschwindigkeit", min: 0.1f),
            new GpsFieldSpec("horizontalExitUpwardImpulse", "Aufwärtsimpuls beim seitlichen Verlassen", min: 0, max: 10)),
        new GpsSectionSpec("Bewegung", "Sprungphysik", typeof(Rigidbody2D), "",
            new GpsFieldSpec("gravityScale", "Gravitationsfaktor"),
            new GpsFieldSpec("mass", "Spielermasse")),
        new GpsSectionSpec("Bewegung", "Itemgewichte", typeof(ItemSO), "",
            new GpsFieldSpec("weight", "Gewicht (kg)")),
        new GpsSectionSpec("Upgrades", "Traglast", typeof(UpgradeSettings), "",
            new GpsFieldSpec("carryingCapacityLevels", "Traglast (kg)")),
        new GpsSectionSpec("Upgrades", "Energiekapazität", typeof(UpgradeSettings), "",
            new GpsFieldSpec("energyCapacityMultipliers", "Energiekapazität (×)")),
        new GpsSectionSpec("Upgrades", "Spitzhacken", typeof(UpgradeSettings), "",
            new GpsFieldSpec("pickaxeLevels", "Spitzhacken")),
        new GpsSectionSpec("Map", "Kartengröße und Seed", typeof(MapGenerator), "",
            new GpsFieldSpec("mapWidth", "Breite (Zellen)", min: 1, max: 10000, applyTime: GpsApplyTime.NewMap),
            new GpsFieldSpec("mapHeight", "Tiefe (Zellen)", min: 1, max: 10000, applyTime: GpsApplyTime.NewMap),
            new GpsFieldSpec("randomizeSeed", "randomizeSeed", applyTime: GpsApplyTime.NewMap),
            new GpsFieldSpec("seed", "Seed", min: -10000000, max: 10000000, applyTime: GpsApplyTime.NewMap)),
        new GpsSectionSpec("Map", "Kartengröße und Seed", typeof(SurfaceTallGrass), "",
            new GpsFieldSpec("healingHerbSpawnAreaSize", "Spawnradius (m)")),
        new GpsSectionSpec("Map", "Weltgrenzen", typeof(MapWorldBorders), "",
            new GpsFieldSpec("sidePaddingCells", "Seitenabstand (Kacheln)", min: 0, max: 10000),
            new GpsFieldSpec("topBorderY", "Obere Grenze (Welt-Y)", min: -10000f)),
        new GpsSectionSpec("Map", "Layer", typeof(MapGenerator), "",
            new GpsFieldSpec("layers", "Layer", applyTime: GpsApplyTime.NewMap)),
        new GpsSectionSpec("Map", "Höhlengeneration", typeof(MapGenerator), "",
            new GpsFieldSpec("caveGeneration", "Höhlengeneration", applyTime: GpsApplyTime.NewMap)),
        new GpsSectionSpec("Map", "Ultronium Altar", typeof(MapGenerator), "",
            new GpsFieldSpec("altarButtonPulseAmplitude", "Pulsamplitude", min: 0f, max: .15f),
            new GpsFieldSpec("altarButtonPulseFrequency", "Pulsfrequenz (Hz)", min: 0f, max: 3f),
            new GpsFieldSpec("altarButtonFloatAmplitude", "Float-Amplitude (Kacheln)", min: 0f, max: .2f),
            new GpsFieldSpec("altarButtonFloatFrequency", "Float-Frequenz (Hz)", min: 0f, max: 3f)),
        new GpsSectionSpec("Map", "Map-Objekte", typeof(MapGenerator), "",
            new GpsFieldSpec("shopSize", "Shop-Größe", min: .25f, max: 3f),
            new GpsFieldSpec("workshopSize", "Workshop-Größe", min: .25f, max: 3f),
            new GpsFieldSpec("altarSize", "Altar-Größe", min: .25f, max: 3f),
            new GpsFieldSpec("energyMonolythSize", "Energy Monolyth-Größe", min: .25f, max: 3f)),
        new GpsSectionSpec("Map", "Map-Objekte", typeof(SurfaceTallGrass), "",
            new GpsFieldSpec("grassSizeMultiplier", "grassSizeMultiplier"),
            new GpsFieldSpec("healingHerbSizeMultiplier", "healingHerbSizeMultiplier")),
        new GpsSectionSpec("Map", "Blockeigenschaften", typeof(MapGenerator), "",
            new GpsFieldSpec("oreScale", "oreScale")),
        new GpsSectionSpec("Map", "Blockeigenschaften", typeof(Block), "",
            new GpsFieldSpec("hardness", "hardness"),
            new GpsFieldSpec("hardnessIndex", "hardnessIndex"),
            new GpsFieldSpec("itemDrop", "Beute-Gegenstand")),
        new GpsSectionSpec("Map", "Untergrund-Hintergrund", typeof(FixedUndergroundBackground), "",
            new GpsFieldSpec("nightBrightnessMultiplier", "Nacht-Helligkeitsfaktor", min: 0f, max: 3f),
            new GpsFieldSpec("yOffset", "Y-Versatz (Welteinheiten)")),
        new GpsSectionSpec("Map", "Blockränder", typeof(UniformStoneAppearance), "",
            new GpsFieldSpec("edgeDepth", "Ausfransungstiefe (×)", min: 0f, max: 2f),
            new GpsFieldSpec("edgeIrregularity", "Unregelmäßigkeit (×)", min: 0f, max: 2f),
            new GpsFieldSpec("edgeRounding", "Eckenrundung (×)", min: 0f, max: 2f),
            new GpsFieldSpec("colliderInset", "Collider-Einzug (Kacheln)", min: 0f, max: .3f)),
        new GpsSectionSpec("Map", "Wandkrümel", typeof(UniformStoneAppearance), "",
            new GpsFieldSpec("rubbleAmount", "Menge pro Blockkante", min: 0f, max: 8f),
            new GpsFieldSpec("rubbleMinSize", "Min. Größe (Kacheln)", min: .02f, max: .6f),
            new GpsFieldSpec("rubbleMaxSize", "Max. Größe (Kacheln)", min: .02f, max: .6f),
            new GpsFieldSpec("rubbleProtrusionPercent", "Überstand (%)", min: 0f, max: 100f)),
        new GpsSectionSpec("Map", "Fackeln", typeof(MapGenerator), "",
            new GpsFieldSpec("torchFlameOffsetX", "Flammenversatz X"),
            new GpsFieldSpec("torchFlameOffsetY", "Flammenversatz Y"),
            new GpsFieldSpec("torchFlameSize", "Flammengröße (×)"),
            new GpsFieldSpec("torchFlameFrequency", "Frequenz (Partikel/s)"),
            new GpsFieldSpec("torchBrightness", "Helligkeit (%)", factor: 100f)),
        new GpsSectionSpec("Erzverteilung", "Map-Overview-Farben", typeof(MapGenerator), "",
            new GpsFieldSpec("mapOverviewColors", "Map-Overview-Farben"),
            new GpsFieldSpec("mapOverviewPlayerColor", "Spieler")),
        new GpsSectionSpec("Erzverteilung", "Globale Verteilung", typeof(MapGenerator), "",
            new GpsFieldSpec("oreDensityCurve", "Tiefenkurve (×)", applyTime: GpsApplyTime.NewMap),
            new GpsFieldSpec("oreDensityMultiplierPercent", "Basis-Erzdichte (%)", min: 0f, max: 100f, applyTime: GpsApplyTime.NewMap)),
        new GpsSectionSpec("Erzverteilung", "Erze", typeof(MapGenerator), "",
            new GpsFieldSpec("useOreSettings", "Erzkonfiguration aktiv", applyTime: GpsApplyTime.NewMap),
            new GpsFieldSpec("oreSettings", "Erze", applyTime: GpsApplyTime.NewMap)),
        new GpsSectionSpec("Partikel", "Ultronium", typeof(MapLighting), "",
            new GpsFieldSpec("ultroniumLightIntensity", "Lichtintensität", min: 0f, max: 1f),
            new GpsFieldSpec("ultroniumPulsesPerMinute", "Pulse pro Minute", min: 0, max: 120),
            new GpsFieldSpec("ultroniumLightColor", "Lichtfarbe"),
            new GpsFieldSpec("ultroniumParticleColor", "Partikelfarbe")),
        new GpsSectionSpec("Partikel", "Item-Feed", typeof(ItemFeed), "",
            new GpsFieldSpec("sparkCount", "Funkenanzahl", min: 0, max: 24),
            new GpsFieldSpec("sparkIntensity", "Funkenintensität", min: 0f, max: 3f),
            new GpsFieldSpec("sparkRiseHeight", "Funkenhöhe (px)", min: 0f, max: 40f),
            new GpsFieldSpec("sparkBrightness", "Funkenhelligkeit", min: 0f, max: 5f),
            new GpsFieldSpec("lineBrightness", "Strichhelligkeit", min: 0f, max: 5f),
            new GpsFieldSpec("backdropOpacity", "Hintergrundabdunklung", min: 0f, max: 1f)),
        new GpsSectionSpec("Partikel", "Blockabbau-Partikel", typeof(BlockBreakParticles), "",
            new GpsFieldSpec("fragmentsPerBlock", "Splitter bei Zerstörung", min: 0, max: 24),
            new GpsFieldSpec("dustPerBlock", "Staub bei Zerstörung", min: 0, max: 16),
            new GpsFieldSpec("fragmentsPerHit", "Splitter pro Treffer", min: 0, max: 12),
            new GpsFieldSpec("dustPerHit", "Staub pro Treffer", min: 0, max: 8)),
        new GpsSectionSpec("Partikel", "Erzfunkeln", typeof(OreSparkles), "",
            new GpsFieldSpec("sparkleMaterial", "Material"),
            new GpsFieldSpec("intervalPerBlock", "Intervall pro Erzblock (s)", min: 0.1f),
            new GpsFieldSpec("darkIntervalMultiplier", "Intervall bei 0 % Licht (×)", min: 1f),
            new GpsFieldSpec("lifetime", "Lebensdauer (s)", min: 0.1f),
            new GpsFieldSpec("size", "Größe", min: 0.02f, max: 1f),
            new GpsFieldSpec("opacity", "Deckkraft", min: 0f, max: 1f),
            new GpsFieldSpec("oreColorStrength", "Erzfarb-Anteil", min: 0f, max: 1f),
            new GpsFieldSpec("brightness", "Helligkeit", min: 1f, max: 8f)),
        new GpsSectionSpec("Licht", "Himmel", typeof(SkyController), "",
            new GpsFieldSpec("SkyFadeDuration", "SkyFadeDuration (s)", min: 0.01f),
            new GpsFieldSpec("automaticCycle", "Automatischer Wechsel"),
            new GpsFieldSpec("DayDuration", "Tagdauer (s)", min: 0.01f),
            new GpsFieldSpec("NightDuration", "Nachtdauer (s)", min: 0.01f),
            new GpsFieldSpec("isNight", "Nacht")),
        new GpsSectionSpec("Licht", "Tageslicht und Dunkelheit", typeof(MapLighting), "",
            new GpsFieldSpec("lightingEnabled", "Beleuchtung aktiv"),
            new GpsFieldSpec("daylightStrength", "Tageslichtstärke", min: 0, max: 1),
            new GpsFieldSpec("ambientBrightness", "Grundhelligkeit im Untergrund", min: 0, max: 1)),
        new GpsSectionSpec("Licht", "Exponentieller Lichtabfall", typeof(MapLighting), "",
            new GpsFieldSpec("exponentialStrength", "exponentialStrength"),
            new GpsFieldSpec("downwardLoss", "Nach unten durch Luft", min: 0.0001f, max: 1),
            new GpsFieldSpec("sidewaysLoss", "Seitlich / nach oben durch Luft", min: 0.0001f, max: 1),
            new GpsFieldSpec("blockLoss", "Zusätzlicher Verlust durch Blöcke", min: 0, max: 1)),
        new GpsSectionSpec("Werkbank", "Rezepte", typeof(CraftingRecipe), "",
            new GpsFieldSpec("category", "Kategorie"),
            new GpsFieldSpec("outputAmount", "Hergestellte Stückzahl", min: 1, max: int.MaxValue),
            new GpsFieldSpec("ingredients", "Zutaten"),
            new GpsFieldSpec("customCardIconLayout", "Eigenes Rezept-Iconlayout"),
            new GpsFieldSpec("cardIconLayout", "Rezept-Iconlayout")),
        new GpsSectionSpec("Werkbank", "Hotbar-Icon", typeof(GpsPreferences), "",
            new GpsFieldSpec("hotbarVerticalOffset", "Iconversatz vertikal", min: -48f, max: 48f)),
        new GpsSectionSpec("Shop", "Erzverkaufspreise", typeof(ItemSO), "",
            new GpsFieldSpec("worth", "Verkaufswert ($)")),
        new GpsSectionSpec("Shop", "Kaufpreise", typeof(CraftingRecipe), "",
            new GpsFieldSpec("shopPrice", "Preis ($)")),
        new GpsSectionSpec("Audio", "Gesamtpegel", typeof(GpsPreferences), "",
            new GpsFieldSpec("masterVolume", "Gesamtlautstärke (%)", min: 0f, max: 1f, factor: 100f)),
        new GpsSectionSpec("Audio", "Rubble", typeof(RubbleAudioSettingsAsset), "",
            new GpsFieldSpec("minimumDelaySeconds", "Versatz min. (s)", min: 0f, max: 10f),
            new GpsFieldSpec("maximumDelaySeconds", "Versatz max. (s)", min: 10f),
            new GpsFieldSpec("nextClipStartPercent", "Nächster Clip ab (%)", min: 0f, max: 100f)),
        new GpsSectionSpec("Audio", "Homescreen", typeof(LoadingAudioSettingsAsset), "",
            new GpsFieldSpec("distantPickaxeVolume") { hideInUi = true },
            new GpsFieldSpec("distantPickaxePitchSpreadPercent") { hideInUi = true },
            new GpsFieldSpec("distantPickaxeVolumeSpreadPercent") { hideInUi = true },
            new GpsFieldSpec("distantPickaxesPerMinute", "Distant Pickaxe pro Minute", min: 0f, max: 60f),
            new GpsFieldSpec("homeClips", "Clips")),
        new GpsSectionSpec("Audio", "Ladebildschirm", typeof(LoadingAudioSettingsAsset), "",
            new GpsFieldSpec("yogaVolume", "Yoga-Lautstärke (%)", factor: 100f),
            new GpsFieldSpec("pickaxeVolume", "Spitzhacke-Lautstärke (%)", factor: 100f),
            new GpsFieldSpec("worldFadeInSeconds", "Spiel-Ambience einblenden (s)", min: 0f, max: 30f),
            new GpsFieldSpec("yogaFadeOutSeconds", "Yoga ausblenden (s)", min: 0f, max: 30f)),
        new GpsSectionSpec("Audio", "Ambience", typeof(AudioManager), "",
            new GpsFieldSpec("ambienceVolume", "Gesamtlautstärke (%)", factor: 100f),
            new GpsFieldSpec("surfaceVolume", "Oberfläche (%)", factor: 100f),
            new GpsFieldSpec("rainVolume", "Regen (%)", factor: 100f),
            new GpsFieldSpec("thunderstormVolume", "Gewitter (%)", factor: 100f),
            new GpsFieldSpec("undergroundVolume", "Untergrund (%)", factor: 100f),
            new GpsFieldSpec("caveVolume", "Höhle (%)", factor: 100f)),
        new GpsSectionSpec("Audio", "Tier-Landungen", typeof(AudioManager), "",
            new GpsFieldSpec("grassLandingOffset", "Zeitversatz (s)", min: -1f, max: 1f)),
        new GpsSectionSpec("Audio", "Abbausounds", typeof(AudioManager), "",
            new GpsFieldSpec("digSoundVolume", "Lautstärke (%)", factor: 100f)),
        new GpsSectionSpec("Audio", "Ding Light", typeof(AudioManager), "",
            new GpsFieldSpec("dingLightVolume", "Lautstärke (%)", factor: 100f),
            new GpsFieldSpec("dingLightOffsetSeconds", "Zeitversatz (s)", min: -10f, max: 10f)),
        new GpsSectionSpec("Audio", "Untergrund-Details", typeof(FirstLayerAmbience), "",
            new GpsFieldSpec("detailsPerMinuteByLayer", "Ereignisse pro Minute je Layer"),
            new GpsFieldSpec("detailsStartDepth", "Ab Tiefe (Blöcke)", min: 0),
            new GpsFieldSpec("detailVolumeMultipliers", "Detailclip-Lautstärke (%)")),
        new GpsSectionSpec("Audio", "Höhlen-Tribal-Song", typeof(SecondLayerAmbience), "",
            new GpsFieldSpec("tribalSongLayer2MeanMinutes", "Ø Minuten in Layer ", min: .01f, max: 120f),
            new GpsFieldSpec("tribalSongLayer3MeanMinutes", "Ø Minuten in Layer ", min: .01f, max: 240f)),
        new GpsSectionSpec("Audio", "Geisterflüstern", typeof(SecondLayerAmbience), "",
            new GpsFieldSpec("ghostWhisperMeanMinutes", "Ø Minuten", min: .01f, max: 120f)),
        new GpsSectionSpec("Audio", "Vogelgezwitscher", typeof(SurfaceBirds), "",
            new GpsFieldSpec("chirpVolume", "Lautstärke (%)", factor: 100f),
            new GpsFieldSpec("chirpsPerMinute", "Rufe pro Minute", min: 0f, max: 120f),
            new GpsFieldSpec("chirpIrregularity", "Unregelmässigkeit", min: 0f, max: 1f)),
        new GpsSectionSpec("Audio", "Froschquaken", typeof(SurfaceCritters), "Frog",
            new GpsFieldSpec("croakVolume", "Lautstärke (%)", factor: 100f),
            new GpsFieldSpec("croaksPerMinute", "Quaks pro Minute", min: 0f, max: 120f),
            new GpsFieldSpec("croakIrregularity", "Unregelmäßigkeit", min: 0f, max: 1f)),
        new GpsSectionSpec("Audio", "Abbauclips pro Layer", typeof(LayerMiningAudioSettingsAsset), "",
            new GpsFieldSpec("entries", "Clips pro Layer")),
        new GpsSectionSpec("Audio", "Einzelclips", typeof(AudioClipTuningSettingsAsset), "",
            new GpsFieldSpec("clips", "Einzelclips")),
        new GpsSectionSpec("Pflanzen", "Bäume", typeof(SurfaceTrees), "",
            new GpsFieldSpec("leafAlpha", "Blatt-Alpha (%)", factor: 100f),
            new GpsFieldSpec("maximumTrees", "Maximale Anzahl", min: 0, max: int.MaxValue),
            new GpsFieldSpec("minimumTreeSpacing", "Mindestabstand (m)"),
            new GpsFieldSpec("hitsToFell", "Treffer zum Fällen", min: 1, max: 100),
            new GpsFieldSpec("fallDurationSeconds", "Fälldauer (s)", min: .1f, max: 10f),
            new GpsFieldSpec("fallRotationCurve", "fallRotationCurve"),
            new GpsFieldSpec("axeHitMultiplier", "Axt-Multiplikator", min: 1f, max: 20f),
            new GpsFieldSpec("woodYieldMin", "Holz mindestens", min: 1, max: 9999),
            new GpsFieldSpec("woodYieldMax", "Holz höchstens", min: 1, max: 9999),
            new GpsFieldSpec("maximumBonusWood", "Max. Bonus-Holz", min: 0),
            new GpsFieldSpec("growthSpeedPercentPerMinute", "Wachstum (% pro Minute)", min: 0f, max: 300f),
            new GpsFieldSpec("maximumSizeBonusPercent", "Max. Größenbonus (%)", min: 0f, max: 200f),
            new GpsFieldSpec("regrowthSeconds", "Nachwuchs min./max. (s)")),
        new GpsSectionSpec("Pflanzen", "Fasergras", typeof(SurfaceTallGrass), "",
            new GpsFieldSpec("maximumPatches", "Menge", min: 0, max: 500),
            new GpsFieldSpec("minimumSpacing", "Mindestabstand (Kacheln)", min: 1, max: 100),
            new GpsFieldSpec("clusterPercent", "clusterPercent"),
            new GpsFieldSpec("clusterSize", "clusterSize"),
            new GpsFieldSpec("randomness", "Zufälligkeit (%)", factor: 100f),
            new GpsFieldSpec("spawnQuietRadius", "Spawnradius (m)", min: 0f, max: 1000f),
            new GpsFieldSpec("nearSpawnDensity", "Menge am Spawn (%)", factor: 100f),
            new GpsFieldSpec("respawnSeconds", "Respawnzeit (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("fiberYield", "Fasern min./max."),
            new GpsFieldSpec("fiberSwayStrength", "Schwankstärke (%)", factor: 100f),
            new GpsFieldSpec("fiberSwayFrequency", "Frequenz (%)", factor: 100f)),
        new GpsSectionSpec("Pflanzen", "Fasergras", typeof(MapGenerator), "",
            new GpsFieldSpec("grassYOffset", "Gras Y-Versatz (Welteinheiten)", min: -.5f, max: .5f)),
        new GpsSectionSpec("Pflanzen", "Heilkraut", typeof(SurfaceTallGrass), "",
            new GpsFieldSpec("healingHerbRarityPercent", "Seltenheit (%)"),
            new GpsFieldSpec("healingHerbConversionLimitPercent", "Umwandlungsgrenze (%)", min: 0f, max: 100f),
            new GpsFieldSpec("healingHerbConversionFactor", "Umwandlungsfaktor", min: 0f, max: 10f),
            new GpsFieldSpec("healingHerbYield", "Heilkraut min./max."),
            new GpsFieldSpec("healingHerbFiberYield", "Fasern min./max."),
            new GpsFieldSpec("healingHerbSwayStrength", "Schwankstärke (%)", factor: 100f),
            new GpsFieldSpec("healingHerbSwayFrequency", "Frequenz (%)", factor: 100f)),
        new GpsSectionSpec("Tiere", "Vögel", typeof(SurfaceBirds), "",
            new GpsFieldSpec("size", "Größe", min: 0.02f, max: 1f),
            new GpsFieldSpec("flockInterval", "Schwarmintervall (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("birdsPerFlock", "Vögel pro Schwarm", min: 1, max: 8),
            new GpsFieldSpec("flightSpeed", "Fluggeschwindigkeit", min: .01f, max: 100f),
            new GpsFieldSpec("altitude", "Flughöhe", min: 0f, max: 100f),
            new GpsFieldSpec("wingbeatsPerSecond", "Flügelschläge pro Sekunde", min: .1f, max: 30f),
            new GpsFieldSpec("nightOffscreenDespawnDelay", "Nacht-Despawn (s)", min: .1f, max: 3600f)),
        new GpsSectionSpec("Tiere", "Häschen", typeof(SurfaceRabbitSpawner), "",
            new GpsFieldSpec("spawnInterval", "Spawnintervall (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("maxRabbits", "Maximale Anzahl", min: 1, max: 20),
            new GpsFieldSpec("despawnDistance", "Despawn-Abstand", min: 2f, max: 10000f),
            new GpsFieldSpec("despawnDelay", "Despawn-Verzögerung (s)", min: .1f, max: 3600f)),
        new GpsSectionSpec("Tiere", "Häschen-Bewegung", typeof(SurfaceRabbit), "",
            new GpsFieldSpec("roamRadius", "Bewegungsradius", min: .5f, max: 1000f),
            new GpsFieldSpec("hopHeight", "Sprunghöhe", min: .1f, max: 100f),
            new GpsFieldSpec("hopDuration", "Sprungdauer (s)", min: .1f, max: 60f),
            new GpsFieldSpec("entryDelay", "Wartezeit vor Auftauchen (s)", min: 0f, max: 3600f),
            new GpsFieldSpec("entryRestDuration", "Pausen beim Reinhoppeln (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("restDuration", "Ruhephasen (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("restInterval", "Abstand zwischen Ruhephasen (s)", min: .1f, max: 3600f)),
        new GpsSectionSpec("Tiere", "Frösche", typeof(SurfaceCritters), "Frog",
            new GpsFieldSpec("maxCount", "Maximale Anzahl", min: 0, max: 12),
            new GpsFieldSpec("spawnInterval", "Spawnintervall (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("restDuration", "Ruhephasen (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("roamRadius", "Bewegungsradius", min: .5f, max: 1000f),
            new GpsFieldSpec("despawnDistance", "Despawn-Abstand", min: 2f, max: 10000f),
            new GpsFieldSpec("despawnDelay", "Despawn-Verzögerung (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("hopHeight", "Sprunghöhe", min: .1f, max: 100f),
            new GpsFieldSpec("hopDuration", "Sprungdauer (s)", min: .1f, max: 60f),
            new GpsFieldSpec("hopDistance", "Sprungweite", min: .1f, max: 100f)),
        new GpsSectionSpec("Tiere", "Schnecken", typeof(SurfaceCritters), "Snail",
            new GpsFieldSpec("maxCount", "Maximale Anzahl", min: 0, max: 12),
            new GpsFieldSpec("spawnInterval", "Spawnintervall (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("restDuration", "Ruhephasen (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("roamRadius", "Bewegungsradius", min: .5f, max: 1000f),
            new GpsFieldSpec("despawnDistance", "Despawn-Abstand", min: 2f, max: 10000f),
            new GpsFieldSpec("despawnDelay", "Despawn-Verzögerung (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("crawlSpeed", "Kriechgeschwindigkeit", min: .01f, max: 100f)),
        new GpsSectionSpec("Tiere", "Glühwürmchen", typeof(SurfaceFireflies), "",
            new GpsFieldSpec("count", "Anzahl", min: 0, max: 80),
            new GpsFieldSpec("cameraMargin", "Abstand ausserhalb der Kamera", min: 0f, max: 1000f),
            new GpsFieldSpec("altitude", "Flughöhe", min: 0f, max: 100f),
            new GpsFieldSpec("flightSpeed", "Fluggeschwindigkeit", min: .01f, max: 100f),
            new GpsFieldSpec("pulseDuration", "Pulsdauer (s)", min: .1f, max: 3600f),
            new GpsFieldSpec("fadeDuration", "Ein-/Ausblenden (s)", min: .1f, max: 3600f)),
        new GpsSectionSpec("Tiere", "Höhlenglühwürmchen", typeof(MapGenerator), "",
            new GpsFieldSpec("caveFireflySpawnRate", "Spawnrate (Gruppen/min)"),
            new GpsFieldSpec("caveFireflyBrightness", "Helligkeit (%)"),
            new GpsFieldSpec("caveFireflyBlue", "Spektrum Blau"),
            new GpsFieldSpec("caveFireflyGreen", "Spektrum Grün"),
            new GpsFieldSpec("caveFireflyYellow", "Spektrum Gelb"),
            new GpsFieldSpec("caveFireflyGroupSizeMin", "Gruppengröße min."),
            new GpsFieldSpec("caveFireflyGroupSizeMax", "Gruppengröße max.")),
        new GpsSectionSpec("Health", "Gesundheit und Fallschaden", typeof(StatsManager), "",
            new GpsFieldSpec("initialHealth", "Initiale Gesundheit (HP)", min: 1f, max: 999999f),
            new GpsFieldSpec("fallDamageHeightBlocks", "Schaden ab Fallhöhe (Blöcke)", min: 0f, max: 1000f),
            new GpsFieldSpec("fallDamageBase", "Basisschaden (+1 Block)", min: 0f, max: 999999f),
            new GpsFieldSpec("fallDamageExponent", "Fallschaden Exponent", min: 1f, max: 5f)),
        new GpsSectionSpec("Health", "Regeneration", typeof(StatsManager), "",
            new GpsFieldSpec("healthRegenPerSecond", "Regeneration (HP/s)", min: 0f, max: 1000f),
            new GpsFieldSpec("healthRegenDelay", "Verzögerung nach Schaden (s)", min: 0f, max: 600f),
            new GpsFieldSpec("healthRegenLimitFraction", "Regeneration bis (%)", factor: 100f)),
        new GpsSectionSpec("Health", "Bildschirm-Effekt", typeof(StatsManager), "",
            new GpsFieldSpec("bloodEdgeIntensity", "Blutrand-Intensität (%)", factor: 100f),
            new GpsFieldSpec("heartbeatFlashIntervalSeconds", "Herzschlag-Intervall bei 25 % (s)", min: .1f, max: 5f),
            new GpsFieldSpec("heartbeatFlashOffsetSeconds", "Herzschlag-Versatz (s)", min: -1f, max: 1f)),
        new GpsSectionSpec("Artefakte", "Artefakte", typeof(MapGenerator), "",
            new GpsFieldSpec("artifactMinimumDepth", "Mindesttiefe (Blöcke)", applyTime: GpsApplyTime.NewMap),
            new GpsFieldSpec("artifactMinimumSameTypeDistance", "Mindestabstand gleicher Artefakte (Blöcke)", applyTime: GpsApplyTime.NewMap),
            new GpsFieldSpec("artifactDropChanceMultiplier", "artifactDropChanceMultiplier", applyTime: GpsApplyTime.NewMap),
            new GpsFieldSpec("artifactEmbeddingStrength", "artifactEmbeddingStrength"),
            new GpsFieldSpec("artifactOverviewIconScale", "artifactOverviewIconScale"),
            new GpsFieldSpec("artifactSettings", "Artefakte", applyTime: GpsApplyTime.NewMap)),
        new GpsSectionSpec("Artefakte", "Artefakt-Animation", typeof(MapGenerator), "",
            new GpsFieldSpec("artifactDiscoveryDurationSeconds", "Dauer (s)"),
            new GpsFieldSpec("artifactDiscoveryArtifactYOffset", "Artefakt Y-Versatz"),
            new GpsFieldSpec("artifactDiscoveryIconRotationFrequency", "Artefakt-Drehfrequenz (Hz)"),
            new GpsFieldSpec("artifactDiscoveryIconRotationAngle", "Artefakt-Drehwinkel (°)"),
            new GpsFieldSpec("artifactDiscoveryShardCount", "Splitter-Anzahl"),
            new GpsFieldSpec("artifactDiscoveryShardDistance", "Splitter-Abstand (%)", factor: 100f),
            new GpsFieldSpec("artifactDiscoveryShardSizeMin", "Splittergröße min."),
            new GpsFieldSpec("artifactDiscoveryShardSizeMax", "Splittergröße max."),
            new GpsFieldSpec("artifactDiscoveryShardRotationFrequency", "Splitter-Drehfrequenz (Hz)"),
            new GpsFieldSpec("artifactDiscoveryShardRotationAngle", "Splitter-Drehwinkel (°)")),
        new GpsSectionSpec("Artefakte", "Iconversatz pro Artefakt", typeof(ArtifactTile), "",
            new GpsFieldSpec("discoveryIconYOffset", "Icon Y-Versatz")),
        new GpsSectionSpec("UI", "Hotbar", typeof(GpsPreferences), "",
            new GpsFieldSpec("hotbarHoldDuration", "Drag-Haltezeit (s)", min: 0f, max: 2f)),
        new GpsSectionSpec("UI", "UI Map", typeof(PlayerMapDiscovery), "",
            new GpsFieldSpec("revealLightThreshold", "Lichtschwelle", min: 0f, max: 1f),
            new GpsFieldSpec("panelAlpha", "Panel-Alpha", min: 0f, max: 1f)),
        new GpsSectionSpec("UI", "GPS-Panel", typeof(GpsPreferences), "",
            new GpsFieldSpec("panelBackdropAlpha", "Hintergrund-Alpha", min: 0f, max: 1f),
            new GpsFieldSpec("panelElementAlpha", "Elemente-Alpha", min: 0f, max: 1f)),
        new GpsSectionSpec("Testeinstellungen", "Testmodus", typeof(GameplayTestSettingsData), "",
            new GpsFieldSpec("testModeDisabled", "Testmodus deaktiviert"),
            new GpsFieldSpec("diggingMultiplierEnabled", "Abbaufaktor aktiv"),
            new GpsFieldSpec("diggingMultiplier", "Abbaufaktor (×)", min: .1f, max: 100f),
            new GpsFieldSpec("movementMultiplierEnabled", "Bewegungsfaktor aktiv"),
            new GpsFieldSpec("movementMultiplier", "Bewegungsfaktor (×)", min: .1f, max: 20f),
            new GpsFieldSpec("godMode", "God Mode"),
            new GpsFieldSpec("noEnergyConsume", "Kein Energieverbrauch"),
            new GpsFieldSpec("flyMode", "Fly Mode"),
            new GpsFieldSpec("noClip", "No Clip"),
            new GpsFieldSpec("noWeight", "Kein Gewicht"),
            new GpsFieldSpec("infiniteMoney", "Unbegrenztes Geld"),
            new GpsFieldSpec("globalLighting", "Global Lighting")),
        new GpsSectionSpec("Testeinstellungen", "Entwicklung", typeof(GameplayTestSettingsData), "",
            new GpsFieldSpec("cameraFollow", "Camera Follow"),
            new GpsFieldSpec("discardPlayedMap", "Map nach Play-Stopp verwerfen")),
    };
}
