if (!UnityEditor.EditorApplication.isPlaying) throw new System.Exception("Play mode required");
var shop=UnityEngine.Object.FindFirstObjectByType<ShopPanel>(UnityEngine.FindObjectsInactive.Include);
shop.ShowPanel(true); shop.ShowBuyPage();
var page=UnityEngine.Object.FindFirstObjectByType<BuyPage>();
var stats=StatsManager.Instance;
var root=page.transform.Find("Blueprint Shop");
var cards=root.Find("Blueprints/Content");
var details=root.Find("Blueprint Details");
var money=page.transform.parent.Find("CurrentMoney/Amount").GetComponent<TMPro.TextMeshProUGUI>();
var purchase=details.Find("Buy Blueprint").GetComponent<UnityEngine.UI.Button>();
var recipes=UnityEngine.Resources.FindObjectsOfTypeAll<CraftingRecipe>().Where(r=>RecipeUnlocks.IsShopRecipe(r)).GroupBy(r=>r.output.item).Select(g=>g.First()).ToArray();
if(cards.childCount!=recipes.Length || cards.childCount!=13) throw new System.Exception("Missing shop blueprints");
var boots=cards.Find("Blueprint HeavyDutyBoots");
boots.GetComponent<UnityEngine.UI.Button>().onClick.Invoke();
var bootRecipe=recipes.First(r=>r.output.item==Item.HeavyDutyBoots);
bootRecipe.TryGetCosts(out var bootCosts);
var materials=details.Find("Materials/Content").Cast<UnityEngine.Transform>().Where(t=>t.gameObject.activeSelf).ToArray();
if(materials.Length!=4 || bootCosts.Count!=4) throw new System.Exception("Expected four actual ingredients");
for(int i=0;i<4;i++) {
    var row=(UnityEngine.RectTransform)materials[i];
    if(row.anchoredPosition!=new UnityEngine.Vector2(i%2*302,-(i/2*102))) throw new System.Exception("Ingredients are not 2x2");
    var cost=bootCosts.ElementAt(i);
    var texts=row.GetComponentsInChildren<TMPro.TextMeshProUGUI>();
    if(texts[0].text!=cost.Key.displayName || texts[1].text!=cost.Value.ToString()) throw new System.Exception("Ingredient mismatch");
}
var scroll=root.Find("Blueprints").GetComponent<UnityEngine.UI.ScrollRect>();
if(scroll.viewport.rect.width!=1250 || scroll.viewport.rect.height!=1002) throw new System.Exception("Grid dimensions");
if(cards.Cast<UnityEngine.Transform>().Count(t=>((UnityEngine.RectTransform)t).anchoredPosition.y>=-680)!=12) throw new System.Exception("Not twelve visible cards");
if(!scroll.verticalScrollbar || scroll.content.rect.height<=scroll.viewport.rect.height) throw new System.Exception("Thirteenth card not scrollable");
page.SetSearch("eIsEnSPITZHACKE");
if(cards.Cast<UnityEngine.Transform>().Count(t=>t.gameObject.activeSelf)!=1 || !cards.Find("Blueprint IronPickaxe").gameObject.activeSelf) throw new System.Exception("Search broken");
page.SetSearch("zzzz-not-a-recipe");
if(details.gameObject.activeSelf || cards.Cast<UnityEngine.Transform>().Any(t=>t.gameObject.activeSelf)) throw new System.Exception("Empty search stale");
page.SetSearch("");
var titanium=cards.Find("Blueprint TitaniumPickaxe");
var recipe=recipes.First(r=>r.output.item==Item.TitaniumPickaxe);
const string key="workbench.recipe.titanium-pickaxe.unlocked";
bool existed=UnityEngine.PlayerPrefs.HasKey(key);
int oldUnlock=UnityEngine.PlayerPrefs.GetInt(key),oldMoney=stats.Money;
var infiniteField=typeof(GameplayTestSettings).GetField("infiniteMoney",System.Reflection.BindingFlags.Static|System.Reflection.BindingFlags.NonPublic);
bool infinite=(bool)infiniteField.GetValue(null);
try {
    infiniteField.SetValue(null,false);
    UnityEngine.PlayerPrefs.DeleteKey(key);
    stats.AddMoney(-stats.Money);
    titanium.GetComponent<UnityEngine.UI.Button>().onClick.Invoke();
    if(purchase.interactable) throw new System.Exception("Unaffordable purchase enabled");
    var price=titanium.GetComponentsInChildren<TMPro.TextMeshProUGUI>()[1];
    if(price.color.r<=price.color.g || price.color.g>=.8f) throw new System.Exception("Missing unaffordable red tint");
    purchase.onClick.Invoke();
    if(RecipeUnlocks.IsTitaniumPickaxeUnlocked || stats.Money!=0) throw new System.Exception("Unaffordable purchase succeeded");
    stats.AddMoney(recipe.ShopPrice+777);
    if(!purchase.interactable || money.text!=ShopMoneyFormatter.Format(recipe.ShopPrice+777)) throw new System.Exception("Money or affordability stale");
    purchase.onClick.Invoke();
    if(!RecipeUnlocks.IsTitaniumPickaxeUnlocked || stats.Money!=777 || purchase.interactable) throw new System.Exception("Purchase state");
    purchase.onClick.Invoke();
    if(stats.Money!=777) throw new System.Exception("Duplicate purchase charged");
    if(((UnityEngine.RectTransform)titanium).anchoredPosition!=new UnityEngine.Vector2(0,-1020)) throw new System.Exception("Owned plan not sorted last");
    shop.ShowSellPage();
    if(!shop.transform.Find("SellPage").gameObject.activeSelf || shop.transform.Find("BuyPage").gameObject.activeSelf) throw new System.Exception("Sell tab broken");
    shop.ShowBuyPage();
    if(!details.Find("Selected Blueprint").GetComponent<UnityEngine.UI.Image>().sprite.name.Contains("Titanium")) throw new System.Exception("Selection lost");
    if(money.text!=ShopMoneyFormatter.Format(777)) throw new System.Exception("Money stale after tabs");
    if(!page.GetComponentsInChildren<TMPro.TextMeshProUGUI>().All(t=>t.font.name=="TitleFont")) throw new System.Exception("Font mismatch");
    return "PASS: 13 plans / 12 visible, scrolling, 2x2 actual ingredients, search and empty state, red unaffordable prices, purchase and duplicate protection, owned sorting, tab selection and live money.";
} finally {
    if(existed) UnityEngine.PlayerPrefs.SetInt(key,oldUnlock); else UnityEngine.PlayerPrefs.DeleteKey(key);
    UnityEngine.PlayerPrefs.Save();
    stats.AddMoney(oldMoney-stats.Money);
    infiniteField.SetValue(null,infinite);
    page.SetSearch("");
    boots.GetComponent<UnityEngine.UI.Button>().onClick.Invoke();
}
